[build]
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"


# Scheduled function for daily CSV import
[[functions]]
  name = "scheduled-import"
  schedule = "0 2 * * *" # Run at 2 AM every day

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"